<?php

namespace Database\Seeders;

use App\Models\Provincia;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProvinciaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $provincias =
        [
            ['departamento_id'=>1,'name'=>'CHACHAPOYAS'],
            ['departamento_id'=>1,'name'=>'BAGUA'],
            ['departamento_id'=>1,'name'=>'BONGARA'],
            ['departamento_id'=>1,'name'=>'CONDORCANQUI'],
            ['departamento_id'=>1,'name'=>'LUYA'],
            ['departamento_id'=>1,'name'=>'RODRIGUEZ DE MENDOZA'],
            ['departamento_id'=>1,'name'=>'UTCUBAMBA'],
            ['departamento_id'=>2,'name'=>'HUARAZ'],
            ['departamento_id'=>2,'name'=>'AIJA'],
            ['departamento_id'=>2,'name'=>'ANTONIO RAYMONDI'],
            ['departamento_id'=>2,'name'=>'ASUNCION'],
            ['departamento_id'=>2,'name'=>'BOLOGNESI'],
            ['departamento_id'=>2,'name'=>'CARHUAZ'],
            ['departamento_id'=>2,'name'=>'CARLOS FERMIN FITZCARRALD'],
            ['departamento_id'=>2,'name'=>'CASMA'],
            ['departamento_id'=>2,'name'=>'CORONGO'],
            ['departamento_id'=>2,'name'=>'HUARI'],
            ['departamento_id'=>2,'name'=>'HUARMEY'],
            ['departamento_id'=>2,'name'=>'HUAYLAS'],
            ['departamento_id'=>2,'name'=>'MARISCAL LUZURIAGA'],
            ['departamento_id'=>2,'name'=>'OCROS'],
            ['departamento_id'=>2,'name'=>'PALLASCA'],
            ['departamento_id'=>2,'name'=>'POMABAMBA'],
            ['departamento_id'=>2,'name'=>'RECUAY'],
            ['departamento_id'=>2,'name'=>'SANTA'],
            ['departamento_id'=>2,'name'=>'SIHUAS'],
            ['departamento_id'=>2,'name'=>'YUNGAY'],
            ['departamento_id'=>3,'name'=>'ABANCAY'],
            ['departamento_id'=>3,'name'=>'ANDAHUAYLAS'],
            ['departamento_id'=>3,'name'=>'ANTABAMBA'],
            ['departamento_id'=>3,'name'=>'AYMARAES'],
            ['departamento_id'=>3,'name'=>'COTABAMBAS'],
            ['departamento_id'=>3,'name'=>'CHINCHEROS'],
            ['departamento_id'=>3,'name'=>'GRAU'],
            ['departamento_id'=>4,'name'=>'AREQUIPA'],
            ['departamento_id'=>4,'name'=>'CAMANA'],
            ['departamento_id'=>4,'name'=>'CARAVELI'],
            ['departamento_id'=>4,'name'=>'CASTILLA'],
            ['departamento_id'=>4,'name'=>'CAYLLOMA'],
            ['departamento_id'=>4,'name'=>'CONDESUYOS'],
            ['departamento_id'=>4,'name'=>'ISLAY'],
            ['departamento_id'=>4,'name'=>'LA UNION'],
            ['departamento_id'=>5,'name'=>'HUAMANGA'],
            ['departamento_id'=>5,'name'=>'CANGALLO'],
            ['departamento_id'=>5,'name'=>'HUANCA SANCOS'],
            ['departamento_id'=>5,'name'=>'HUANTA'],
            ['departamento_id'=>5,'name'=>'LA MAR'],
            ['departamento_id'=>5,'name'=>'LUCANAS'],
            ['departamento_id'=>5,'name'=>'PARINACOCHAS'],
            ['departamento_id'=>5,'name'=>'PAUCAR DEL SARA SARA'],
            ['departamento_id'=>5,'name'=>'SUCRE'],
            ['departamento_id'=>5,'name'=>'VICTOR FAJARDO'],
            ['departamento_id'=>5,'name'=>'VILCAS HUAMAN'],
            ['departamento_id'=>6,'name'=>'CAJAMARCA'],
            ['departamento_id'=>6,'name'=>'CAJABAMBA'],
            ['departamento_id'=>6,'name'=>'CELENDIN'],
            ['departamento_id'=>6,'name'=>'CHOTA'],
            ['departamento_id'=>6,'name'=>'CONTUMAZA'],
            ['departamento_id'=>6,'name'=>'CUTERVO'],
            ['departamento_id'=>6,'name'=>'HUALGAYOC'],
            ['departamento_id'=>6,'name'=>'JAEN'],
            ['departamento_id'=>6,'name'=>'SAN IGNACIO'],
            ['departamento_id'=>6,'name'=>'SAN MARCOS'],
            ['departamento_id'=>6,'name'=>'SAN MIGUEL'],
            ['departamento_id'=>6,'name'=>'SAN PABLO'],
            ['departamento_id'=>6,'name'=>'SANTA CRUZ'],
            ['departamento_id'=>7,'name'=>'CALLAO'],
            ['departamento_id'=>8,'name'=>'CUSCO'],
            ['departamento_id'=>8,'name'=>'ACOMAYO'],
            ['departamento_id'=>8,'name'=>'ANTA'],
            ['departamento_id'=>8,'name'=>'CALCA'],
            ['departamento_id'=>8,'name'=>'CANAS'],
            ['departamento_id'=>8,'name'=>'CANCHIS'],
            ['departamento_id'=>8,'name'=>'CHUMBIVILCAS'],
            ['departamento_id'=>8,'name'=>'ESPINAR'],
            ['departamento_id'=>8,'name'=>'LA CONVENCION'],
            ['departamento_id'=>8,'name'=>'PARURO'],
            ['departamento_id'=>8,'name'=>'PAUCARTAMBO'],
            ['departamento_id'=>8,'name'=>'QUISPICANCHI'],
            ['departamento_id'=>8,'name'=>'URUBAMBA'],
            ['departamento_id'=>9,'name'=>'HUANCAVELICA'],
            ['departamento_id'=>9,'name'=>'ACOBAMBA'],
            ['departamento_id'=>9,'name'=>'ANGARAES'],
            ['departamento_id'=>9,'name'=>'CASTROVIRREYNA'],
            ['departamento_id'=>9,'name'=>'CHURCAMPA'],
            ['departamento_id'=>9,'name'=>'HUAYTARA'],
            ['departamento_id'=>9,'name'=>'TAYACAJA'],
            ['departamento_id'=>10,'name'=>'HUANUCO'],
            ['departamento_id'=>10,'name'=>'AMBO'],
            ['departamento_id'=>10,'name'=>'DOS DE MAYO'],
            ['departamento_id'=>10,'name'=>'HUACAYBAMBA'],
            ['departamento_id'=>10,'name'=>'HUAMALIES'],
            ['departamento_id'=>10,'name'=>'LEONCIO PRADO'],
            ['departamento_id'=>10,'name'=>'MARAÑON'],
            ['departamento_id'=>10,'name'=>'PACHITEA'],
            ['departamento_id'=>10,'name'=>'PUERTO INCA'],
            ['departamento_id'=>10,'name'=>'LAURICOCHA'],
            ['departamento_id'=>10,'name'=>'YAROWILCA'],
            ['departamento_id'=>11,'name'=>'ICA'],
            ['departamento_id'=>11,'name'=>'CHINCHA'],
            ['departamento_id'=>11,'name'=>'NASCA'],
            ['departamento_id'=>11,'name'=>'PALPA'],
            ['departamento_id'=>11,'name'=>'PISCO'],
            ['departamento_id'=>12,'name'=>'HUANCAYO'],
            ['departamento_id'=>12,'name'=>'CONCEPCION'],
            ['departamento_id'=>12,'name'=>'CHANCHAMAYO'],
            ['departamento_id'=>12,'name'=>'JAUJA'],
            ['departamento_id'=>12,'name'=>'JUNIN'],
            ['departamento_id'=>12,'name'=>'SATIPO'],
            ['departamento_id'=>12,'name'=>'TARMA'],
            ['departamento_id'=>12,'name'=>'YAULI'],
            ['departamento_id'=>12,'name'=>'CHUPACA'],
            ['departamento_id'=>13,'name'=>'TRUJILLO'],
            ['departamento_id'=>13,'name'=>'ASCOPE'],
            ['departamento_id'=>13,'name'=>'BOLIVAR'],
            ['departamento_id'=>13,'name'=>'CHEPEN'],
            ['departamento_id'=>13,'name'=>'JULCAN'],
            ['departamento_id'=>13,'name'=>'OTUZCO'],
            ['departamento_id'=>13,'name'=>'PACASMAYO'],
            ['departamento_id'=>13,'name'=>'PATAZ'],
            ['departamento_id'=>13,'name'=>'SANCHEZ CARRION'],
            ['departamento_id'=>13,'name'=>'SANTIAGO DE CHUCO'],
            ['departamento_id'=>13,'name'=>'GRAN CHIMU'],
            ['departamento_id'=>13,'name'=>'VIRU'],
            ['departamento_id'=>14,'name'=>'CHICLAYO'],
            ['departamento_id'=>14,'name'=>'FERREÑAFE'],
            ['departamento_id'=>14,'name'=>'LAMBAYEQUE'],
            ['departamento_id'=>15,'name'=>'LIMA'],
            ['departamento_id'=>15,'name'=>'BARRANCA'],
            ['departamento_id'=>15,'name'=>'CAJATAMBO'],
            ['departamento_id'=>15,'name'=>'CANTA'],
            ['departamento_id'=>15,'name'=>'CAÑETE'],
            ['departamento_id'=>15,'name'=>'HUARAL'],
            ['departamento_id'=>15,'name'=>'HUAROCHIRI'],
            ['departamento_id'=>15,'name'=>'HUAURA'],
            ['departamento_id'=>15,'name'=>'OYON'],
            ['departamento_id'=>15,'name'=>'YAUYOS'],
            ['departamento_id'=>16,'name'=>'MAYNAS'],
            ['departamento_id'=>16,'name'=>'ALTO AMAZONAS'],
            ['departamento_id'=>16,'name'=>'LORETO'],
            ['departamento_id'=>16,'name'=>'MARISCAL RAMON CASTILLA'],
            ['departamento_id'=>16,'name'=>'REQUENA'],
            ['departamento_id'=>16,'name'=>'UCAYALI'],
            ['departamento_id'=>16,'name'=>'DATEM DEL MARAÑON'],
            ['departamento_id'=>16,'name'=>'PUTUMAYO'],
            ['departamento_id'=>17,'name'=>'TAMBOPATA'],
            ['departamento_id'=>17,'name'=>'MANU'],
            ['departamento_id'=>17,'name'=>'TAHUAMANU'],
            ['departamento_id'=>18,'name'=>'MARISCAL NIETO'],
            ['departamento_id'=>18,'name'=>'GENERAL SANCHEZ CERRO'],
            ['departamento_id'=>18,'name'=>'ILO'],
            ['departamento_id'=>19,'name'=>'PASCO'],
            ['departamento_id'=>19,'name'=>'DANIEL ALCIDES CARRION'],
            ['departamento_id'=>19,'name'=>'OXAPAMPA'],
            ['departamento_id'=>20,'name'=>'PIURA'],
            ['departamento_id'=>20,'name'=>'AYABACA'],
            ['departamento_id'=>20,'name'=>'HUANCABAMBA'],
            ['departamento_id'=>20,'name'=>'MORROPON'],
            ['departamento_id'=>20,'name'=>'PAITA'],
            ['departamento_id'=>20,'name'=>'SULLANA'],
            ['departamento_id'=>20,'name'=>'TALARA'],
            ['departamento_id'=>20,'name'=>'SECHURA'],
            ['departamento_id'=>21,'name'=>'PUNO'],
            ['departamento_id'=>21,'name'=>'AZANGARO'],
            ['departamento_id'=>21,'name'=>'CARABAYA'],
            ['departamento_id'=>21,'name'=>'CHUCUITO'],
            ['departamento_id'=>21,'name'=>'EL COLLAO'],
            ['departamento_id'=>21,'name'=>'HUANCANE'],
            ['departamento_id'=>21,'name'=>'LAMPA'],
            ['departamento_id'=>21,'name'=>'MELGAR'],
            ['departamento_id'=>21,'name'=>'MOHO'],
            ['departamento_id'=>21,'name'=>'SAN ANTONIO DE PUTINA'],
            ['departamento_id'=>21,'name'=>'SAN ROMAN'],
            ['departamento_id'=>21,'name'=>'SANDIA'],
            ['departamento_id'=>21,'name'=>'YUNGUYO'],
            ['departamento_id'=>22,'name'=>'MOYOBAMBA'],
            ['departamento_id'=>22,'name'=>'BELLAVISTA'],
            ['departamento_id'=>22,'name'=>'EL DORADO'],
            ['departamento_id'=>22,'name'=>'HUALLAGA'],
            ['departamento_id'=>22,'name'=>'LAMAS'],
            ['departamento_id'=>22,'name'=>'MARISCAL CACERES'],
            ['departamento_id'=>22,'name'=>'PICOTA'],
            ['departamento_id'=>22,'name'=>'RIOJA'],
            ['departamento_id'=>22,'name'=>'SAN MARTIN'],
            ['departamento_id'=>22,'name'=>'TOCACHE'],
            ['departamento_id'=>23,'name'=>'TACNA'],
            ['departamento_id'=>23,'name'=>'CANDARAVE'],
            ['departamento_id'=>23,'name'=>'JORGE BASADRE'],
            ['departamento_id'=>23,'name'=>'TARATA'],
            ['departamento_id'=>24,'name'=>'TUMBES'],
            ['departamento_id'=>24,'name'=>'CONTRALMIRANTE VILLAR'],
            ['departamento_id'=>24,'name'=>'ZARUMILLA'],
            ['departamento_id'=>25,'name'=>'CORONEL PORTILLO'],
            ['departamento_id'=>25,'name'=>'ATALAYA'],
            ['departamento_id'=>25,'name'=>'PADRE ABAD'],
            ['departamento_id'=>25,'name'=>'PURUS']
        ];
        foreach ($provincias as $provincia) {
            Provincia::create($provincia);
        }
    }
}
